mode: editor
create_show_note: true
components:
  - audio:
      path: 'J:\PodCast\sound_resource\side-B\intro.wav'
  - audio_placeholder:
      index: 0
      var: 0
  - audio_placeholder:
      index: 0
      var: 1
  - audio:
      path: 'J:\PodCast\sound_resource\side-B\ending.wav'

note:
  type: "B"
  tag: 'side-B'
  template: |-
    # A
    # B
    # C


publish:
  explicit: true
