mode: s2t2s
publish:
  thumbnail: 'config/yoshi_zunda.png'

note:
  type: "A"
  tag: 'side-A'
  template: |-
    # A
    # B
    # C

speak:
  labels:
    - id: "3"
      name: "まっと"
    - id: "2"
      name: "大久保"